/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package crud;
import clases.GeneroClass;

import java.util.List;
import javax.persistence.EntityManager;
import javax.persistence.EntityManagerFactory;
import javax.persistence.Persistence;
import javax.persistence.Query;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class GenroCrud extends javax.swing.JInternalFrame {
    
    
        EntityManagerFactory emf = null;
        EntityManager em = null;
        
        private int filaSeleccionada = -1;

    /**
     * Creates new form GeneroGui
     */
    public GenroCrud() {
                initComponents();
                emf = Persistence.createEntityManagerFactory("C:/base/Practica.odb");
                em = emf.createEntityManager();
                listarm();        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        genero = new javax.swing.JTextField();
        guardar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel3 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        seleccionar = new javax.swing.JButton();
        editar = new javax.swing.JButton();

        setClosable(true);
        setIconifiable(true);
        setMaximizable(true);
        setResizable(true);

        jLabel1.setText("Registrar Genero de libro");

        jLabel2.setText("Nombre:");

        guardar.setText("GUARDAR");
        guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                guardarActionPerformed(evt);
            }
        });

        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tabla);

        jLabel3.setText("Nombre de los generos:");

        jButton1.setText("BORRAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        seleccionar.setText("SELECCIONAR");
        seleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seleccionarActionPerformed(evt);
            }
        });

        editar.setText("EDITAR");
        editar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(guardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton1))
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addGap(33, 33, 33)
                        .addComponent(genero))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(seleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(editar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 87, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 452, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(25, 25, 25))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(genero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(guardar)
                            .addComponent(jButton1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(seleccionar)
                            .addComponent(editar)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(121, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
   
    public GeneroClass crearlibro(){   
        String generol = genero.getText();
        
        GeneroClass L = new GeneroClass(generol);
   
        return L;
    }
    private void guardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_guardarActionPerformed
        // TODO add your handling code here:
        em = emf.createEntityManager(); // Crear un nuevo EntityManager
        GeneroClass L = crearlibro();
        try {
            em.getTransaction().begin();
            em.persist(L);
            em.getTransaction().commit();
        } catch (Exception ex) {
                    ex.printStackTrace();
        } finally {
                        em.close();
        }
        listarm();
           // Limpia los campos de texto
            genero.setText("");
    }//GEN-LAST:event_guardarActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
              // TODO add your handling code here:
               int filaSeleccionada = tabla.getSelectedRow();
                if (filaSeleccionada != -1) {
                    String genero = (String) tabla.getValueAt(filaSeleccionada, 0);

                    em = emf.createEntityManager();
                    try {
                        em.getTransaction().begin();
                        Query query = em.createQuery("DELETE FROM GeneroClass l WHERE l.nombre = :genero");
                        query.setParameter("genero", genero);
                        query.executeUpdate();
                        em.getTransaction().commit();
                        JOptionPane.showMessageDialog(this, "Registro eliminado correctamente", "Eliminación exitosa", JOptionPane.INFORMATION_MESSAGE);
                   
                    } catch (Exception ex) {
                        ex.printStackTrace();
                    } finally {
                        em.close();
                    }

                    listarm();
                    
                }

    }//GEN-LAST:event_jButton1ActionPerformed

    private void seleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seleccionarActionPerformed
        // TODO add your handling code here:
               // Obtiene la fila seleccionada
            filaSeleccionada = tabla.getSelectedRow();

        // Verifica si se seleccionó una fila
        if (filaSeleccionada != -1) {
            // Obtiene los datos de la fila seleccionada
            String generoSeleccionado = (String) tabla.getValueAt(filaSeleccionada, 0);

            // Muestra los datos en los campos de texto
            genero.setText(generoSeleccionado);
        }
    }//GEN-LAST:event_seleccionarActionPerformed

    private void editarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editarActionPerformed
               // TODO add your handling code here:
          if (filaSeleccionada != -1) {
            String nuevoGenero = genero.getText();

            em = emf.createEntityManager();
            try {
                em.getTransaction().begin();
                Query query = em.createQuery("UPDATE GeneroClass l SET l.nombre = :nuevoGenero WHERE l.nombre = :genero");
                query.setParameter("nuevoGenero", nuevoGenero);
                query.setParameter("genero", tabla.getValueAt(filaSeleccionada, 0));
                query.executeUpdate();
                em.getTransaction().commit();

                JOptionPane.showMessageDialog(this, "Cambios guardados correctamente", "Edición exitosa", JOptionPane.INFORMATION_MESSAGE);
            } catch (Exception ex) {
                ex.printStackTrace();
            } finally {
                em.close();
            }

            // Restablece el valor de la variable de fila seleccionada
            filaSeleccionada = -1;

            // Limpia los campos de texto
            genero.setText("");

            listarm();
        }
    }//GEN-LAST:event_editarActionPerformed

        public void listarm() {
        em = emf.createEntityManager(); // Crear un nuevo EntityManager.
        try {
            Query ConsultaLibro = em.createQuery("SELECT m FROM GeneroClass m");
            List<GeneroClass> ResultadosLibro = ConsultaLibro.getResultList();

            DefaultTableModel modelo = (DefaultTableModel) tabla.getModel();
            modelo.setRowCount(0);
            for (GeneroClass libro : ResultadosLibro) {
                modelo.addRow(new Object[]{libro.getNombre()});
            }
        } catch (Exception ex) {
                    ex.printStackTrace();
        } finally {
            em.close();
        }

    }
        
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton editar;
    private javax.swing.JTextField genero;
    private javax.swing.JButton guardar;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton seleccionar;
    private javax.swing.JTable tabla;
    // End of variables declaration//GEN-END:variables
}
